### PR TITLE
Use Jupyter Notebook and Binder environment

### PR DESCRIPTION
**Pull request by sgibson91**
Hey @DLetch!

I found this quite difficult to get started with, especially since I'm not familiar with R/RStudio (wasn't sure where I was supposed to be clicking!), I didn't have the right things installed locally (and didn't know how to install them!), and trying to work with both the PDF and RStudio open was difficult. I kind of wanted an experience where I could read a little bit about what was happening and then execute some code that demonstrated it. So I've transformed your script into a Jupyter Notebook and provided an environment file with all the dependencies listed. What this means that the repo is now compatible with Binder so I don't have to have anything installed locally!

You can run it all in Binder here -> https://mybinder.org/v2/gh/DLetch/Data-Visualisation-Project/sgibson91/jupyter-binder?filepath=CovidPartnerPlots.ipynb

If you'd like to see it in RStudio instead, follow this link -> https://mybinder.org/v2/gh/DLetch/Data-Visualisation-Project/sgibson91/jupyter-binder?urlpath=rstudio

I think to improve this from here, the script should be split up into "chunks" (or cells as they're called in Jupyter Notebooks!), where each cell does a specific thing e.g. plot a particular graph. And then have the text that is currently in your PDF interspersed as Markdown cells so that everything appears as one document.

Let me know if I can help explain this further and/or contribute more to tidying it up!

### CODE REVIEW

**Comment by DLetch** [comment]
@sgibson91 Thank you for looking through this that's a massive help!! 

I had a couple of really quick questions regarding the environment/ dependencies and how it works as I haven't used that before. Would it be alright to have a quick call just to clear up any questions I have. If I try explain over here I'll probably make no sense.

Thanks!

**Comment by sgibson91** [comment]
I've accepted your meeting invite and of course I'm happy to answer any Q's. There's also this video of me explaining how Binder works from EuroPython this year: https://www.youtube.com/watch?v=wTVMHallSSA (This is Python specific but works for R too using similar principles) You can also check out this tutorial I co-wrote with an R user http://bit.ly/zero-to-binder-r

**Comment by DLetch** [comment]
@sgibson91 Hi Sarah, I'm trying to work out how to save my changes on the script in Juypter Binder so that they get pushed out to this GitHub. When I save it the changes don't appear when I re open to juypter notebook so I feel like I'm missing a step. Do you know where I may be going wrong?

I've also somehow managed to merge a pull request in the process, does this mess anything up at all? I was hoping this would make my changes appear but get the feeling this wasn't the correct step.

Thanks!

**Comment by sgibson91** [comment]
Hi Daisy - Binder cannot push changes back to GitHub as it is a public service and push access requires credentials which we (the operating team) can't take responsibility for. Instead of doing "File -> Save changes", there'll be a "Download Notebook" (or something similarly named) button along the top menu, towards the right-hand side. This will download the Notebook locally so that you can add it GitHub in the same way you added your Rscript, etc.

Merging the Pull Request just means you have accepted the changes I suggested into your `main` branch (the default). Which isn't the worst thing in the world, but I don't think I left it in the tidiest state 😬 When you upload your changes, you can just upload it to the main branch.

It does change the Binder link you'll need to use -> https://mybinder.org/v2/gh/DLetch/Data-Visualisation-Project/HEAD?filepath=CovidPartnerPlots.ipynb

I can add a "launch binder" button to your README that will automatically update for you.

**Comment by DLetch** [comment]
Oh yes I see now that makes sense thank you! 

If you're able to add the 'launch binder' button that would be really helpful thank you :)

**Comment by sgibson91** [comment]
Done! :) https://github.com/DLetch/Data-Visualisation-Project/blob/main/README.md

**Pull request merged**
